services:
  # A private Minio instance
  - type: web
    name: simple-go-server
    env: go
    repo: https://github.com/scottnuma/simple-go-server.git
    disk:
      name: data
      mountPath: /data
      sizeGB: 50 # optional
    startCommand: ./app
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
  - type: redis
    name: lightning
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
