services:
  # A private Minio instance
  - type: web
    name: simple-go-server
    env: go
    repo: https://github.com/scottnuma/simple-go-server.git
    disk:
      name: data
      mountPath: /data
      sizeGB: 50 # optional
    startCommand: ./app
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
